language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:

    - cpanm --notest --skip-satisfied Dist::Zilla

    - dzil authordeps         | cpanm --notest --skip-satisfied
    - dzil listdeps --author  | cpanm --notest --skip-satisfied

script:
    - dzil test --all
